import { Inter } from "next/font/google";
import styles from "../../components/layout/layout.module.css";
import Link from "next/link";
import '../app/globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ashkan Jay Next Project",
  description: "Generated by Next14",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <Link href="/">
            <h2>Ashkan Car Project</h2>
            <p>Choose and buy your car here !</p>
          </Link>
        </header>
        <div className={styles.container}>{children}</div>

        <footer className={styles.footer}>
          Designed & Developed by Ashkan Jay with Love
        </footer>
      </body>
    </html>
  );
}
